---

- name: Install vim
  become: true
  ansible.builtin.apt:
    name: vim
    state: present
    update_cache: true
    force: true
  when: 'ansible_os_family == "Debian"'

- name: Create .vim & colors folders
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.vim/colors"
    state: directory
    mode: '0755'

- name: Create plugins folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ ansible_env.HOME }}/.vim/pack/tpope/start"
    - "{{ ansible_env.HOME }}/.vim/pack/pasky/start"

- name: Get surround plugin
  ansible.builtin.git:
    repo: "https://github.com/tpope/vim-surround"
    dest: "{{ ansible_env.HOME }}/.vim/pack/tpope/start/surround"
    version: v2.2

- name: Get commentary plugin
  ansible.builtin.git:
    repo: "https://github.com/tpope/vim-commentary"
    dest: "{{ ansible_env.HOME }}/.vim/pack/tpope/start/commentary"
    version: 64a654e

- name: Get claude plugin
  ansible.builtin.git:
    repo: "https://github.com/pasky/claude.vim"
    dest: "{{ ansible_env.HOME }}/.vim/pack/pasky/start/claude.vim"
    version: 06baac1

- name: Write vimrc
  ansible.builtin.template:
    src: templates/vimrc.j2
    dest: "{{ ansible_env.HOME }}/.vimrc"
    mode: '0755'

- name: Wombat256 color scheme
  ansible.builtin.template:
    src: "templates/wombat256.j2"
    dest: "{{ ansible_env.HOME }}/.vim/colors/wombat256.vim"
    mode: '0755'

...
